[package]
name = "ci"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = "2.9.0"
rustnix = "0.0.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
structstruck = "0.5.0"
