[package]
name = "render"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
data = { version = "0.1.0", path = "../data" }
futures-signals = "0.3.34"
reqwasm = "0.5.0"
serde_json = "1.0.140"
silkenweb = "0.10.0"
web-log = { version = "1.0.1", features = ["std"] }
